### ISSUE TITLE
directory listing without trailing slash redirects to incorrect location

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry-incubator/staticfile-buildpack#13]
When `Staticfile` has `directory: visible` enabled, if you visit a directory without a trailing slash the app tries to redirect to the URL with the trailing slash. With CloudFoundry, it appends the port of the app on to the URL.

Steps to recreate:

```sh
mkdir fancy_dir/
touch bert.txt
echo 'directory: visible' > Staticfile
cf push my-app -b https://github.com/cloudfoundry-incubator/staticfile-buildpack
open http://my-app.cf-apps.io/fancy_dir
```

Noticed that the directory does not properly redirect.

**Comment by flavorjones** [comment]
@jtarchie Can you check if #12 fixes the issue you're reporting? Thanks!

**Comment by jtarchie** [comment]
It is fixed on latest master. Closing,
