### ISSUE TITLE
how can I add a text/cache-manifest mime type

### ISSUE THREAD

**Issue by hairmare** [cloudfoundry-incubator/staticfile-buildpack#16]
I'd like to add a mime type to serve a ``text/cache-manifest`` manifest file from my app.

I'm trying to create a html5 offline app. I could use the php buildpack to accomplish this, but it seems like overkill given this app has no local ``NETWORK`` resources in the manifest.

If you would accept this in mime.types globally I'll do a pull request ASAP.

**Comment by drnic** [comment]
If you can find an example nginx snippet on the Internet for this then it can be merged into the nginx.conf being used here. Possible for you to do that?

**Comment by hairmare** [comment]
I added an example in #17. It's in mime.types rather than nginx.conf.

**Comment by edmorley** [comment]
If it helps in the meantime, you should also be able to create a custom ``mime.types``:
https://github.com/cloudfoundry-incubator/staticfile-buildpack/blob/caa6cea1527f4bc8720ee566ff1c4f99331746c1/bin/compile#L52

I've added this to the README in #25.

**Comment by hairmare** [comment]
#25 helps a lot and perfectly answers my original question so I'm closing this issue.

It's nice to know that I can override the ``nginx.conf`` as well.

I'm keeping #17 open since I still believe having it as default might have its merits. Feel free to close it if you feel otherwise.
